spring:
  config:
    import: "optional:classpath:application-dev-local.yml"

sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 127.0.0.1
    port: 3307
    database: sky_take_out
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2000ms
    database: 0

security:
  password:
    bcrypt-cost: 12